
# Site settings (used in header)
title: Deep Patel
description: >
    Deep Patel is a full-time student and web developer. He creates
    websites, JavaScript apps, and more.
baseurl: ""

# Build settings
exclude: ["README.md", "default site", "portfolio.sublime-project", "portfolio.sublime-workspace", "originals"]
permalink: pretty
gems:
  - jekyll-sitemap