
# Site settings
title: Deep Patel | Portfolio
description: >
    This is Deep Patel's personal website. View my projects, android themes,
    and read my Kustom tutorials here.
baseurl: ""

# Build settings
exclude: ["README.md", "default site", "portfolio.sublime-project", "portfolio.sublime-workspace", "originals"]
permalink: pretty
gems:
  - jekyll-sitemap